// Canonical block type labels used across admin UI
export const blockTypeLabels: Record<string, string> = {
  'hero': 'Hero',
  'chat-hero': 'Chat Hero ✨',
  'about-split': 'About Me',
  'text-section': 'Text Section',
  'cta-banner': 'CTA Banner',
  'image-text': 'Image & Text',
  'spacer': 'Spacer',
  'featured-carousel': 'Featured',
  'expertise-grid': 'Expertise',
  'skills-bar': 'Skills Bar ✨',
  'values': 'Values ✨',
  'project-showcase': 'Projects',
  'chat-widget': 'Chat',
  'video-hero': 'Video Hero ✨',
  'parallax-section': 'Parallax ✨',
  'bento-grid': 'Bento Grid ✨',
  'marquee': 'Marquee ✨',
  'stats-counter': 'Stats ✨',
  'testimonial-carousel': 'Testimonials ✨',
  'contact-form': 'Contact Form',
  'blog': 'Blog Posts',
  'newsletter-subscribe': 'Newsletter',
  'github': 'GitHub Repos',
};
