import { ConversationMessage, ResponseLength } from '../types';
import { Model, AnalysisResult } from '@/utils/openRouter';
import { ScenarioType } from '../types';

export interface LabsState {
  apiKey: string;
  savedApiKey: string;
  userApiKey: string;
  isSaving: boolean;
  isSaved: boolean;
  isUsingEnvKey: boolean;
  agentAModel: string;
  agentBModel: string;
  agentCModel: string;
  agentAPersona: string;
  agentBPersona: string;
  agentCPersona: string;
  rounds: number;
  numberOfAgents: number;
  responseLength: ResponseLength;
  conversation: ConversationMessage[];
  isLoading: boolean;
  availableModels: Model[];
  loadingModels: boolean;
  currentStep: number;
  activeScenario: string;
  promptInputs: Record<string, string>;
  isAnalyzing: boolean;
  analysisResults: AnalysisResult | null;
  analyzerModel: string;
}

export interface LabsActions {
  setApiKey: (key: string) => void;
  setSavedApiKey: (key: string) => void;
  setUserApiKey: (key: string) => void;
  setIsSaving: (saving: boolean) => void;
  setIsSaved: (saved: boolean) => void;
  setAgentAModel: (model: string) => void;
  setAgentBModel: (model: string) => void;
  setAgentCModel: (model: string) => void;
  setAgentAPersona: (persona: string) => void;
  setAgentBPersona: (persona: string) => void;
  setAgentCPersona: (persona: string) => void;
  setRounds: (rounds: number) => void;
  setNumberOfAgents: (number: number) => void;
  setResponseLength: (length: ResponseLength) => void;
  setConversation: (conversation: ConversationMessage[]) => void;
  setIsLoading: (loading: boolean) => void;
  setAvailableModels: (models: Model[]) => void;
  setLoadingModels: (loading: boolean) => void;
  setCurrentStep: (step: number) => void;
  setActiveScenario: (scenario: string) => void;
  setPromptInputs: (inputs: Record<string, string>) => void;
  setIsAnalyzing: (analyzing: boolean) => void;
  setAnalysisResults: (results: AnalysisResult | null) => void;
  setAnalyzerModel: (model: string) => void;
  handleInputChange: (scenarioId: string, key: string, value: string) => void;
  saveApiKey: () => Promise<boolean>;
  deleteApiKey: () => void;
  getActiveApiKey: (modelIsFree?: boolean) => string | null;
  goToStep: (step: number) => void;
  handleStartConversation: () => Promise<void>;
  handleAnalyzeConversation: (model?: string) => Promise<void>;
  handleAgentAPersonaChange: (e: React.ChangeEvent<HTMLSelectElement>) => void;
  handleAgentBPersonaChange: (e: React.ChangeEvent<HTMLSelectElement>) => void;
  handleAgentCPersonaChange: (e: React.ChangeEvent<HTMLSelectElement>) => void;
  getCurrentScenario: () => ScenarioType;
  getCurrentPrompt: () => string;
  formatMessage: (message: string) => string;
}
